controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

accepter:
    path: '/cart/success/{id}'
    controller: 'App\Controller\CartController::paymentSuccess'
    methods: ['GET']
    

annuler:
    path: '/cart/cancel/{id}'
    controller: 'App\Controller\CartController::paymentCancel'
    methods: ['GET']

app_confirme:
    path: '/admin/confirme/{id}'
    controller: 'App\Controller\Admin\DashboardController::sendConfirmationEmail'

download_pdf:
    path: '/dashboard/fichierPdf/{id}'
    controller: App\Controller\ReservationController::downloadPDF
    methods: ['GET']
 
# Route pour la page de contact
app_contact:
    path: '/contact'
    controller: App\Controller\ContactController::index
     

app_allcars_:
    path: '/allcars'
    controller: App\Controller\AllcarsController::index
    

app_register:
    path: '/register'
    controller: App\Controller\RegistrationController::register

app_facture:
    path: '/admin/facture'
    controller: 'App\Controller\Admin\DashboardController::facturation'
    

 
